{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8c354103-7798-4026-97c7-67d316cebaca",
   "metadata": {},
   "outputs": [],
   "source": [
    "1. Python, an exception is an event that occurs during the execution of a program that disrupts the normal\n",
    "flow of the program's instructions. When an exception occurs, it typically results in the termination of\n",
    "the program, unless it is handled properly. \n",
    "\n",
    " Syntax errors are detected by the Python interpreter during the parsing phase, before the program is executed.\n",
    "Exceptions, on the other hand, occur during the execution of the program when certain\n",
    "conditions are met."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b23ba3e6-c7af-4208-a5ab-cb096159fc08",
   "metadata": {},
   "outputs": [],
   "source": [
    "2.When an exception is not handled in Python, it results in the termination of the program and an error message\n",
    "is displayed, indicating the type of exception that occurred and the traceback information. This abrupt \n",
    "termination without proper handling can leave the program in an inconsistent state and prevent it from \n",
    "completing its intended tasks.\n",
    "#without exeception\n",
    "\n",
    "def divide_numbers(a, b):\n",
    "    result = a / b\n",
    "    return result\n",
    "num1 = 10\n",
    "num2 = 0\n",
    "\n",
    "# Call the function without exception handling\n",
    "result = divide_numbers(num1, num2)\n",
    "print(result)\n",
    "\n",
    "\n",
    "\n",
    "#with exception\n",
    "def divide_numbers(a, b):\n",
    "    try:\n",
    "        result = a / b\n",
    "        return result\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Error: Cannot divide by zero!\")\n",
    "\n",
    "num1 = 10\n",
    "num2 = 0\n",
    "\n",
    "# Call the function with exception handling\n",
    "result = divide_numbers(num1, num2)\n",
    "print(result)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4c0430dd-2651-43ca-aa25-9f5f5ef00d76",
   "metadata": {},
   "outputs": [],
   "source": [
    "3.#try & else\n",
    "def divide_numbers(a, b):\n",
    "    try:\n",
    "        result = a / b\n",
    "        return result\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Error: Cannot divide by zero!\")\n",
    "\n",
    "num1 = 10\n",
    "num2 = 0\n",
    "\n",
    "# Call the function with exception handling\n",
    "result = divide_numbers(num1, num2)\n",
    "print(result)\n",
    "\n",
    "In Python, the try and else statements are used together to handle exceptions in a more controlled and \n",
    "structured manner. The try block allows you to enclose a section of code that might raise an exception, \n",
    "while the else block allows you to specify code that should be executed if no exception occurs within\n",
    "the try block.\n",
    "\n",
    "\n",
    "#finaly\n",
    "In Python, the finally block is used in conjunction with the try and except blocks to define code that \n",
    "should be executed regardless of whether an exception occurred or not. The finally block ensures that \n",
    "certain cleanup operations or essential actions are performed, whether an exception is raised or\n",
    "not.\n",
    "\n",
    "def divide_numbers(a, b):\n",
    "    try:\n",
    "        result = a / b\n",
    "        print(\"The division result is:\", result)\n",
    "    except ZeroDivisionError:\n",
    "        print(\"Error: Cannot divide by zero!\")\n",
    "    finally:\n",
    "        print(\"Cleanup: Division operation completed.\")\n",
    "\n",
    "# Test cases\n",
    "divide_numbers(10, 2)  # No exception occurs\n",
    "divide_numbers(10, 0)  # Raises ZeroDivisionError\n",
    "\n",
    "\n",
    "\n",
    "#raise\n",
    "In Python, the raise statement is used to explicitly raise an exception. It allows you to create and\n",
    "raise custom exceptions or propagate built-in exceptions in specific situations. The raise statemen\n",
    "t is followed by an exception object or class that represents the type of exception being raised.\n",
    "\n",
    "\n",
    "\n",
    "class CustomException(Exception):\n",
    "    pass\n",
    "\n",
    "def process_data(data):\n",
    "    if not data:\n",
    "        raise CustomException(\"No data available!\")\n",
    "    else:\n",
    "        # Process the data\n",
    "\n",
    "# Test case\n",
    "data = []\n",
    "try:\n",
    "    process_data(data)  # Raises CustomException\n",
    "except CustomException as e:\n",
    "    print(\"An exception occurred:\", str(e))\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "927c8a5f-611d-4d67-99dd-8be370f061d0",
   "metadata": {},
   "outputs": [],
   "source": [
    "5.Custom exceptions in Python are user-defined exception classes that inherit from the base Exception\n",
    "class or one of its subclasses. They allow developers to create specific types of exceptions that are\n",
    "tailored to their application's requirements and provide meaningful error messages or additional\n",
    "attributes. \n",
    "\n",
    "class InvalidInputException(Exception):\n",
    "    def __init__(self, message):\n",
    "        self.message = message\n",
    "\n",
    "def process_data(data):\n",
    "    if not data:\n",
    "        raise InvalidInputException(\"Invalid input data!\")\n",
    "    else:\n",
    "        # Process the data\n",
    "\n",
    "# Test case\n",
    "data = []\n",
    "try:\n",
    "    process_data(data)  # Raises InvalidInputException\n",
    "except InvalidInputException as e:\n",
    "    print(\"An exception occurred:\", str(e))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e51f9f64-d2b4-4170-a95b-27260599e784",
   "metadata": {},
   "outputs": [],
   "source": [
    "6."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4b3edadd-91b5-4877-b388-aa0c4d1ee015",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
